#!/usr/bin/python3
#This script is for removing unwanted lines from HTML files
#which have been exported from confluence
#this can be saved as a template for filters when building docs

import sys
import re

myFile = sys.argv[1]
myTarget = open(sys.argv[2], 'w')
myOutput = open('webCleanOutput.txt', 'w')
out = ""


data =  open(myFile, 'r', encoding = None, errors = 'ignore')
myPage = "<!doctype html> "
toggleDelete = False
#myPage = []

#cut lines containing unwanted text string
for line in data:
     if isinstance(line, str) == True:
        #print("true")

        if 'class="author"' in line or "class='author'" in line:
            out += "DELETED:"
            out += line
            continue
        if 'class="editor"' in line or "class='editor'" in line:
            out += "DELETED:"
            out += line
            continue
        if '<!DOCTYPE html>' in line:
            out += "DELETED:"
            out += line
            continue
        if '<body' in line:
            out += "DELETED:"
            out += line
            continue
        if '</body' in line:
            out += "DELETED:"
            out += line
            continue
        if '</html' in line:
            out += "DELETED:"
            out += line
            continue
        if '<html' in line:
            out += "DELETED:"
            out += line
            continue
        if '<META' in line:
            out += "DELETED:"
            out += line
            continue
        if '<!DOCTYPE html>' in line:
            out += "DELETED:"
            out += line
            continue
        if '<title' in line:
            out += "DELETED:"
            out += line
            continue
        if '<meta' in line:
            out += "DELETED:"
            out += line
            continue
        if '<head' in line:
            out += "DELETED:"
            out += line
            continue
        if '</head' in line:
            out += "DELETED:"
            out += line
            continue
        if 'id="footer"' in line or 'class="footer-body"' in line or 'id="footer-logo"' in line:
            out += "DELETED:"
            out += line
            continue
        if 'Document generated by Confluence' in line:
            out += "DELETED:"
            out += line
            continue
        if '<link' in line:
            out += "DELETED:"
            out += line
            continue
# These lines removed the Confluence-generated TOC
        if 'toc-macro' in line or 'toc-indentation' in line or 'breadcrumb-section' in line or 'breadcrumbs' in line:

            toggleDelete = True
            out += "Menu delete is on because of this line: "
            out += line
            line.replace("toc", "###")
            line.replace("breadcrumb", "###")
            myPage += line
            continue
        if "href='#" in line:
            out += "DELETED:"
            out += line
            continue
        if toggleDelete == True and '</ul>' in line:
            toggleDelete = False
            out += "Menu delete is off (found /UL):"
            out += line
            continue
        if toggleDelete == True and '</ol>' in line:
            toggleDelete = False
            out += "Menu delete is off (found /OL):"
            out += line
            continue
        if toggleDelete == True:
            out += "DELETED:"
            out += line
            continue
# Last line writes the content to the clean version of document
        else:
#           print("PROCESSED: ", line)
           myPage += line

           #myPage.append(line)
     else:
        print("not string")

#create output file
#myPage.encode('utf-8')
#myPage.encode('windows-1252')


data2 = myPage
tempPage=str(myPage)
#print(tempPage)
for line in data2:
   myTarget.write(line)
for line in out:
    myOutput.write(line)


print("webClean script completed.")
